services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:mysql://backend_database:3306/freelance_be
      - minio.endpoint=http://minio:9000
    ports:
      - "9000:9000"
    networks:
      - freelance_be
  database:
    container_name: backend_database
    image: mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=freelance_be
      - MYSQL_ROOT_PASSWORD=Godfather@2.0
    networks:
      - freelance_be
    healthcheck:
      test: "mysql --user=root --password=Godfather@2.0"
  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9081:9001
      - 127.0.0.1:9080:9000
    environment:
      - console-address=:9001
    # volumes:
    #   - C:\Users\mrvnt\docker\minio\data:/data
    networks:
      - freelance_be
networks:
  freelance_be: